# Taskfile.yml

version: "3"

tasks:
  build:
    desc: build mssql develop environment
    cmds: 
      - task: db-mssql-start
      - task: db-mssql-init-db
      - task: db-mssql-init-table
      - task: db-mssql-init-data
  
  build-mysql:
    desc: build mysql develop environment
    cmds: 
      - task: db-mysql-start







  db-mssql-start:
    desc: start mssql at local
    cmds:
      - docker-compose -f ./Docker-Compose/docker-compose.mssql.yml up -d mssql

  db-mysql-start:
    desc: start mysql at local
    cmds:
      - docker-compose -f ./Docker-Compose/docker-compose.mysql.yml up -d mysql

  db-mssql-init-db:
    desc: create mssql database
    deps: [db-mssql-start]
    cmds:
      - docker cp ./DataBase/sample.sql sample-db-mssql:/sample.sql
      - docker exec sample-db-mssql /opt/mssql-tools/bin/sqlcmd -S sample-db-mssql -U sa -P Sample01 -i ./sample.sql
      - timeout 5

  db-mssql-init-table:
    desc: create mssql table_schema
    deps: [db-mssql-init-db]
    cmds:
      - docker cp ./DataBase/PolicyHolder.sql sample-db-mssql:/PolicyHolder.sql
      - docker cp ./DataBase/PolicyHolder_BinaryTree.sql sample-db-mssql:/PolicyHolder_BinaryTree.sql
      - docker exec sample-db-mssql /opt/mssql-tools/bin/sqlcmd -S sample-db-mssql -U sa -P Sample01 -i ./PolicyHolder.sql
      - docker exec sample-db-mssql /opt/mssql-tools/bin/sqlcmd -S sample-db-mssql -U sa -P Sample01 -i ./PolicyHolder_BinaryTree.sql

  db-mssql-init-data:
    desc: insert mssql data
    deps: [db-mssql-init-table]
    cmds:
      - docker cp ./DataBase/data.sql sample-db-mssql:/data.sql
      - docker exec sample-db-mssql /opt/mssql-tools/bin/sqlcmd -S sample-db-mssql -U sa -P Sample01 -i ./data.sql