version: "3.8"

networks:
  Sample_Network:

secrets:
  my_access_key:
    external: true
  my_secret_key:
    external: true
services:  
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sample-db-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sample01
    ports:
      - 1433:1433
    networks:
      - Sample_Network