version: "3.8"

networks:
  Sample_Network:

services:
  mysql:
    image: mysql:latest
    container_name: sample-db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_USER: dev
      MYSQL_PASSWORD: sample
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: